pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'Villager-Interface'
includeBuild('../Authorization-Common')
include 'network-authorization'
project(':network-authorization').projectDir = file('../Network-Authorization/fabric')
