plugins {
    id 'java-library'
}
group = 'com.silver'
version = '1.0.0'
base { archivesName = 'pretty-chat-api' }
repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}
dependencies {
    compileOnly 'com.velocitypowered:velocity-api:3.4.0-SNAPSHOT'
}
java {
    toolchain { languageVersion = JavaLanguageVersion.of(25) }
    withSourcesJar()
}
tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}
