plugins { id 'application' }

group = 'com.silver'
version = '0.1.0-SNAPSHOT'

java { toolchain { languageVersion = JavaLanguageVersion.of(25) } }
application { mainClass = 'com.silver.openpacpruner.Main' }

repositories { mavenCentral() }
dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
tasks.named('test') { useJUnitPlatform() }
