plugins {
    id 'java'
    id 'com.gradleup.shadow'
}

group = 'com.silver'
version = '1.0.0'
base { archivesName = 'chronicle-velocity' }
java { toolchain { languageVersion = JavaLanguageVersion.of(25) } }
sourceSets.main.java.srcDir '../common/src/main/java'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'com.velocitypowered:velocity-api:4.1.2-SNAPSHOT'
    annotationProcessor 'com.velocitypowered:velocity-api:4.1.2-SNAPSHOT'
    compileOnly 'org.slf4j:slf4j-api:2.0.13'
    implementation 'com.zaxxer:HikariCP:7.0.2'
    implementation 'org.mariadb.jdbc:mariadb-java-client:3.5.7'
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}
tasks.shadowJar {
    archiveBaseName.set('chronicle-velocity')
    archiveClassifier.set('')
    mergeServiceFiles()
}
tasks.jar {
    archiveBaseName.set('chronicle-velocity')
    archiveClassifier.set('thin')
}
