package com.silver.aipets.fabric.transfer;

public enum PetTransferStatus {
    NO_PET,
    HELD_UNCHANGED,
    LEFT_BEHIND,
    SOURCE_PREPARED,
    SOURCE_ALREADY_PREPARED,
    DESTINATION_NOT_RESERVED,
    DESTINATION_EXPIRED,
    DESTINATION_NO_SAFE_POSITION,
    DESTINATION_PLACED,
    DESTINATION_SPAWN_FAILED_COMPENSATED,
    DESTINATION_SPAWN_FAILED_UNRESOLVED,
    AUTHORITY_REJECTED,
    PLAYER_CONTEXT_CHANGED,
    SERVICE_FAILURE
}
