plugins {
	id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

sourceSets {
	main {
		java.srcDirs = ['src/main/java']
		resources.srcDirs = ['src/main/resources']
		java.exclude '**/enderdragons/mixins/EntityTrackerMixin.java'
		java.exclude '**/giantmobs/mixins/EntityTrackerMixin.java'
		java.exclude '**/nocreepers/mixins/MobSpawnerLogicMixin.java'
	}
}

repositories {
	// Additional repos can go here if needed.
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"sky_islands" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	implementation "com.silver:mc-portal-protocol:1.0.0"
}

processResources {
	inputs.property "version", project.version
	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}
}
