plugins {
    id 'net.fabricmc.fabric-loom'
}
group = 'com.silver'
version = project.mod_version
base { archivesName = 'pretty-chat-fabric' }
loom {
    splitEnvironmentSourceSets()
    mods { 'prettychat' { sourceSet sourceSets.main } }
}
sourceSets.main.java.srcDir '../common/src/main/java'
dependencies {
    minecraft('com.mojang:minecraft:' + project.minecraft_version)
    implementation('net.fabricmc:fabric-loader:' + project.loader_version)
    implementation('net.fabricmc.fabric-api:fabric-api:' + project.fabric_version)
}
processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand version: project.version }
}
java { toolchain { languageVersion = JavaLanguageVersion.of(25) }; withSourcesJar() }
tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}
