plugins {
    id 'fabric-loom'
    id 'maven-publish'
}

base {
    archivesName = 'pet-companion'
}

loom {
    splitEnvironmentSourceSets()
}

sourceSets {
    testmod {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
    }
}

loom {
    mods {
        'pet_companion' {
            sourceSet sourceSets.main
        }
        'pet_companion_test' {
            sourceSet sourceSets.testmod
        }
    }

    runs {
        testmodServer {
            server()
            name 'Pet Companion Testmod Server'
            source sourceSets.testmod
        }
        gametest {
            inherit testmodServer
            name 'Pet Companion Game Test'
            vmArg '-Dfabric-api.gametest'
            vmArg "-Dfabric-api.gametest.report-file=${layout.buildDirectory.file('gametest-results.xml').get().asFile}"
            if (providers.gradleProperty('gametestFilter').isPresent()) {
                vmArg "-Dfabric-api.gametest.filter=${providers.gradleProperty('gametestFilter').get()}"
            }
            runDir 'build/gametest'
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    implementation project(':pet-common')
    include project(':pet-common')

    testmodImplementation sourceSets.main.output
    testmodImplementation project(':pet-service')

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.3'
    testImplementation project(':pet-service')
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.3'
}

tasks.named('runGametest') {
    outputs.file layout.buildDirectory.file('gametest-results.xml')
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
