plugins {
    id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT' apply false
}

allprojects {
    group = project.maven_group
    version = project.mod_version

    repositories {
        mavenCentral()
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    }
}

subprojects {
    tasks.withType(JavaCompile).configureEach {
        options.release = 25
        options.encoding = 'UTF-8'
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}
